config/routes.rb
Rails.application.routes.draw do
  get 'lectures/show'
  devise_for :users
  get 'subjects/show'
  get 'pages/index'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root to: 'pages#index'
  get '/home', to: 'pages#home'

  resources :subjects do
    resources :notes, only: [:show] do
      resources :comments
    end
    resources :lectures, only: [:show] do
      resources :appoinments, only: %i[new destroy]
      # get '/:lecture_id/appoinment/new', to: 'appoinments#create'
      # delete '/:lecture_id/appoinment/delete', to: 'appoinments#destroy'
    end
  end
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/appoinment.rb
class Appoinment < ApplicationRecord
  belongs_to :lecture
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :note
  has_rich_text :content
end

app/models/lecture.rb
class Lecture < ApplicationRecord
  belongs_to :subject
  has_many :users
  has_many :appoinments, dependent: :destroy
end

app/models/note.rb
class Note < ApplicationRecord
  belongs_to :subject
  has_many :comments, dependent: :destroy
end

app/models/subject.rb
class Subject < ApplicationRecord
  has_many :notes
  has_many :lectures, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :comments, dependent: :destroy
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!

  def update
    logger.info "\n\n\n comments controller update action with params \n #{params} \n\n\n"

    @note = Note.find(params[:note_id])
    @comment = @note.comments.find(params[:id])

    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to subject_note_path(@note.subject, @note), notice: 'Your feedback was updated' }
      else
        format.html { redirect_to subject_note_path(@note.subject, @note), notice: 'Your feedback was not updated' }
      end
    end
  end

  def create
    logger.info "\n\n\n comments controller create action with params \n #{params} \n\n\n"

    @note = Note.find(params[:note_id])
    comment = @note.comments.new(comment_params)
    comment.user = current_user

    if comment.save
      flash[:notice] = 'comment is created'
      redirect_to subject_note_path(@note.subject, @note)
    else
      flash[:alert] = 'comment is not created'
      redirect_to subject_note_path(@note.subject, @note)
    end
  end

  def destroy
    logger.info "\n\n\n comments controller destroy action with params \n #{params} \n\n\n"

    comment = Comment.find(params[:id])
    return unless comment.destroy

    flash[:notice] = 'comment is deleted'
    redirect_to subject_note_path(comment.note.subject, comment.note)
  end

  private

  def comment_params
    params.require(:comment).permit(:content)
  end
end

app/controllers/lectures_controller.rb
class LecturesController < ApplicationController
  def show
    logger.info "\n\n lectures conroller show action with params \n #{params} \n\n"
    @lecture = Lecture.find(params[:id])
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  def show
    logger.info "\n\n Notes controller show action running \n with params : #{params} \n\n"
    @note = Note.find(params[:id])
    @comments = Comment.where(note_id: params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @subjects = Subject.all
  end

  def index
    @appoinments = Appoinment.where(user_id: current_user.id) if user_signed_in?
  end
end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  def show
    logger.info "\n\n Subjects controller show action running \n with params : #{params} \n\n"
    @subject = Subject.find(params[:id])
    @notes = @subject.notes
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appoinments_helper.rb
module AppoinmentsHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/lectures_helper.rb
module LecturesHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.erb
<div class="jumbotron bg-light p-3 my-3">
  <p class="mb-0 fs-6 text-muted"><%= comment.user.email %> said</p>

  <% if (comment.updated_at - comment.created_at) > 1 %>
    <p class="mb-2">
      <small class="mb-3">edited <%= time_ago_in_words(comment.created_at) %> ago</small>  
    </p>
  <% else %>
    <p class="mb-2">
      <small class="mb-3">posted <%= time_ago_in_words(comment.created_at) %> ago</small>
    </p>
  <% end %>

  <div id="comment-content-<%= comment.id %>" class="px-2">
    <p><%= comment.content %></p>
  </div>
  
  <% if current_user == comment.user %>
    <div class="d-flex">
      <%= button_to 'Delete your feedback', subject_note_comment_path(comment.note.subject, comment.note, comment), method: :delete, class:"btn btn-outline-danger btn-sm me-2" %>

      <%= link_to 'Edit your feedback', nil, 
        remote:true, 
        class:"btn btn-outline-primary btn-sm ms-2", 
        data: {
          controller: 'comments',
          action: "comments#toggleForm",
          comments_form_param: "edit-form-#{comment.id}",
          comments_content_param: "comment-content-#{comment.id}"
        }
      %>
    </div>
  <% end %>

  <div id="edit-form-<%= comment.id %>" class="d-none mt-3">
    <%= render 'comments/update_form', comment:comment %>
  </div>
</div>

app/views/comments/_form.html.erb
<%= form_with model:[note.subject, note, note.comments.build] do |f| %>
  <div class='form-control'>
    <%= f.rich_text_area :content %>
    <div class="d-flex flex-row-reverse">
      <%= f.submit 'Make a feedback', class: 'btn btn-sm btn-secondary mt-3' %>
    </div>
  </div>
<% end %>

app/views/comments/_update_form.html.erb
<%= form_with model:[comment.note.subject, comment.note, comment] do |f| %>
  <div class='form-control'>
    <%= f.rich_text_area :content %>
    <div class="d-flex flex-row-reverse">
      <%= f.submit 'Make a feedback', class: 'btn btn-sm btn-secondary mt-3' %>
    </div>
  </div>
<% end %>

app/views/lectures/show.html.erb
<div class="jumbotron bg-light p-4">
  <div class="container">
    <h1 class="display-5"><%= @lecture.topic.capitalize %></h1>
    <h5>Conducted by : <%= @lecture.instructor %></h5>
    <p class="mb-0">Date and time: <%= @lecture.time %></p>
    
    <div class="d-flex flex-row justify-content-between align-items-center mt-5 my-2">
      <h6 class=" me-5 mb-0">Available seats: 
        <%= @lecture.max_appoinments - (@lecture.appoinments.length) %></h6>
    </div>

    <div class="d-flex gap-3 justify-content-start">
      <%= link_to 'Reserve your seat',  new_subject_lecture_appoinment_path(@lecture.subject, @lecture), class:'btn btn-primary rounded mt-4' %>
      <%= button_to 'Remove your reservation',  subject_lecture_appoinment_path(@lecture.subject, @lecture), method: :delete, class:'btn btn-outline-danger rounded mt-4' %>
    </div>

  </div>
</div>

app/views/notes/show.html.erb
<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <h1 class="display-4"><%= @note.title %></h1>
    <h6>Created on : <%= @note.created_at %></h6>

    <p class="lead"><%= @note.body %></p>
    <%= link_to subject_path(@note.subject) do%>
      <button class='btn btn-primary rounded mt-4'>Back to <%= @note.subject.name %></button>
    <% end %>
  </div>
</div>

<div class="jumbotron p-3 mt-5">
  <h2 class="fw-light">Student feedbacks</h2>
  <p class="lead">This is a simple hero unit, a simple jumbotron-style component for calling extra attention to featured content or information.</p>
  <hr class="my-4">

  <div class="my-3 bg-light p-3">
    <%= render 'comments/form', note:@note %>
  </div>
  
  <% if @comments.length >= 1 %>
    <% @comments.each do |comment| %>
      <%= render 'comments/comment', {comment:comment} %>
    <% end %>
  <% end %>
  
</div>

app/views/subjects/show.html.erb
<div class="jumbotron bg-light p-3">
  <h1 class="display-4">Hello, welcome to <%= @subject.name %>!</h1>
  <p class="lead">This is a simple hero unit, a simple jumbotron-style component for calling extra attention to featured content or information.</p>
  <hr class="my-4">
  <p>It uses utility classes for typography and spacing to space content out within the larger container.</p>
  
  <p class="lead">
    <%= link_to home_path do%>
      <button class="btn btn-primary btn-lg">Back to courses</button>
    <% end %>
  </p>
</div>


<div class="jumbotron mt-5">
  <h1 class="display-6">Available notes</h1>
  <hr class="my-4">
  <p>It uses utility classes for typography and spacing to space content out within the larger container.</p>
  
  <% @subject.notes.each do |note| %>
    <div class="d-flex flex-row justify-content-between align-items-center bg-light my-2 p-2">
      <h6 class=" me-auto mb-0"><%= note.title %></h6>
      <p class=' mb-0 me-5'><%= note.body.truncate(80) %></p>
      <%= link_to subject_note_path(@subject, note) do%>
        <button class='btn btn-primary rounded'>read more</button>
      <% end %>
    </div>
  <% end %>
</div>

<div class="jumbotron mt-5">
  <h1 class="display-6">Available lecture sessions</h1>
  <hr class="my-4">
  <p>It uses utility classes for typography and spacing to space content out within the larger container.</p>
  
  <% @subject.lectures.each do |lecture| %>
    <div class="d-flex flex-row justify-content-between align-items-center bg-light my-2 p-2">
      <h6 class=" mb-0"><%= lecture.subject.name %></h6>
      <h6 class=" mb-0">Topic: <%= lecture.topic %></h6>
      <p class=' mb-0 '>Instructor: <%= lecture.instructor %></p>
      <p class=' mb-0 '>Time: <%= lecture.time %></p>
      <%= link_to subject_lecture_path(@subject, lecture) do%>
        <button class='btn btn-outline-success rounded'>Book your Seat</button>
      <% end %>
    </div>
  <% end %>
</div>

app/views/users/_session_manager.html.erb
<% if current_user %>

  <li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
      <%= current_user.email %>
    </a>
    <ul class="dropdown-menu " aria-labelledby="navbarDropdownMenuLink">
      <li class="dropdown-item">
        <%= link_to 'New post', root_path, class: 'nav-link text-dark' %>
      </li>
      <li class="dropdown-item">
        <%= link_to 'Edit acount', edit_user_registration_path, class: 'nav-link text-dark' %>
      </li>
      <li><hr class="dropdown-divider"></li>
      <li class="dropdown-item">
        <%= button_to 'Log out', destroy_user_session_path, method: :delete, class: 'btn btn-sm btn-outline-danger mx-auto' %>
      </li>
    </ul>
  </li>

<% else %>
    <%= link_to 'Create account', new_user_registration_path, class: 'btn btn-sm btn-secondary mb-1 mx-1' %>
    <%= link_to 'Sign up', new_user_session_path, class: 'btn btn-sm btn-primary mb-1 mx-1' %>
<% end %>