config/routes.rb
Rails.application.routes.draw do
  get 'lectures/show'
  devise_for :users
  get 'subjects/show'
  get 'pages/index'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root to: 'pages#index'
  get '/home', to: 'pages#home'

  resources :subjects do
    resources :notes, only: [:show] do
      resources :comments
    end
    resources :lectures, only: [:show] do
      resources :appoinments, only: %i[new destroy]
      # get '/:lecture_id/appoinment/new', to: 'appoinments#create'
      # delete '/:lecture_id/appoinment/delete', to: 'appoinments#destroy'
    end
  end
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/appoinment.rb
class Appoinment < ApplicationRecord
  belongs_to :lecture
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :note
  has_rich_text :content
end

app/models/lecture.rb
class Lecture < ApplicationRecord
  belongs_to :subject
  has_many :users
  has_many :appoinments, dependent: :destroy
end

app/models/note.rb
class Note < ApplicationRecord
  belongs_to :subject
  has_many :comments, dependent: :destroy
end

app/models/subject.rb
class Subject < ApplicationRecord
  has_many :notes
  has_many :lectures, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :comments, dependent: :destroy
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  def show
    logger.info "\n\n Notes controller show action running \n with params : #{params} \n\n"
    @note = Note.find(params[:id])
    @comments = Comment.where(note_id: params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @subjects = Subject.all
  end

  def index
    @appoinments = Appoinment.where(user_id: current_user.id) if user_signed_in?
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appoinments_helper.rb
module AppoinmentsHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/lectures_helper.rb
module LecturesHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/layouts/_navbar.html.erb
<header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark text-light mb-4">
        <div class="container">
          <%= link_to 'NoteBook', root_path, class: 'navbar-brand' %>

          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav">
              <li class="nav-item">
                <%= link_to 'Discover', home_path, class: 'nav-link text-decorations-none' %>
              </li>
              <li class="nav-item">
                <%= link_to 'Manage Content', new_admin_user_session_path, class: 'nav-link text-decorations-none' %>
              </li>
            </ul>
          </div>
          
          <ul class='navbar-nav'>
            <%= render 'users/session_manager' %>
          </ul>
        </div>
      </nav>
    </header>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Notebook</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <div class="container-md">
      <% if notice%>
        <div class="alert alert-warning alert-dismissible fade show" role="alert">
          <p class="notice mb-0"><%= notice %></p>
          <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
      <% end %>

      <% if alert %>
        <div class="alert alert-warning alert-dismissible fade show" role="alert">
          <p class="alert mb-0"><%= alert %></p>
          <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
      <% end %>
      
      <%= yield %>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
  </body>
</html>

app/views/pages/_subject_card.html.erb
<div class="card bg-light shadow-sm my-3">
  <img src="https://picsum.photos/id/237/768/1080" class="card-img-top img-fluid" alt="course image">

  <div class="card-body">
    <h5 class="card-title"><%= subject.name %></h5>
    <p class="card-text"><%= subject.intro.truncate(100) %></p>
    
    <%= link_to subject_path(subject) do%>
      <button class="btn btn-primary">Find more about  
        <%= subject.name %>
      </button>
    <% end %>
  </div>
</div>

app/views/pages/home.html.erb
<h2 class="align-center mb-4">Recently Added Notes</h2>

  <div class="row justify-content-start flex-wrap">
    <% @subjects.each do |subject| %>
      <div class="col-lg-4">
          <%= render 'pages/subject_card', {subject: subject} %>
      </div>
    <%end%>

</div>

app/views/pages/index.html.erb
<h1>Welcome <%= current_user ? current_user.email : "to Notebook" %></h1>
<p class="mb-5">Find me in app/views/pages/index.html.erb</p>

<h3 class="mt-5 mb-4 fw-normal">Your lecture sessions</h3>

<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th scope="col">Subject</th>
      <th scope="col">Lecture topic</th>
      <th scope="col">Time</th>
      <th scope="col">Instructor</th>
    </tr>
  </thead>
    <% if @appoinments && @appoinments.length > 0 %>  
      <tbody>
        <% @appoinments.each do |appoinment| %>
          <tr>
            <td><%= link_to appoinment.lecture.subject.name, subject_path(appoinment.lecture.subject) %></td>
            <td><%= link_to appoinment.lecture.topic, subject_lecture_path(appoinment.lecture.subject, appoinment.lecture) %></td>
            <td><%= appoinment.lecture.time %></td>
            <td><%= appoinment.lecture.instructor %></td>   
          </tr>
        <% end %>
      </tbody>
    <% end %>
</table>

<% unless @appoinments && @appoinments.length > 0 %>
  <div class="d-flex flex-row justify-content-center align-items-center bg-light p-5">
    <h4 class=" my-5">You haven't reserved any seats for lecture sessions</h4>
  </div>
<% end %>